# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)

        #Preferred： 缺省大小是最佳效果，部件允许放大或缩小，但不倾向于扩展比sizeHint()大
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)

        #设置水平方向上的大小策略
        # 0：QSizePolicy::Fixed   控件的大小固定为sizeHint的推荐大小，不能在改变；
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        # setHeightForWidth()函数的标志表示部件的缺省大小（sizeHint()）是否是width-dependent
        #总之就是一堆Policy，先不管
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(872, 536))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")



        # 关于前进后退按钮
        self.next_prev = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_prev.sizePolicy().hasHeightForWidth())
        self.next_prev.setSizePolicy(sizePolicy)
        self.next_prev.setMaximumSize(QtCore.QSize(1920, 16777215))
        self.next_prev.setStyleSheet("")
        self.next_prev.setLineWidth(1)
        self.next_prev.setObjectName("next_prev")
        self.prev_next = QtWidgets.QHBoxLayout(self.next_prev)
        self.prev_next.setContentsMargins(0, 0, 0, 0)
        self.prev_next.setSpacing(6)
        self.prev_next.setObjectName("prev_next")
        self.prev_button = QtWidgets.QPushButton(self.next_prev)
        self.prev_button.setObjectName("prev_button")
        self.prev_next.addWidget(self.prev_button)
        self.next_button = QtWidgets.QPushButton(self.next_prev)
        self.next_button.setObjectName("next_button")
        self.prev_next.addWidget(self.next_button)
        self.gridLayout.addWidget(self.next_prev, 3, 3, 1, 1)




        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame#frame{border:1px solid #828790}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        #水平布局
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)

        # 设置左侧、顶部、右侧和底部边距，以便在布局周围使用。
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addWidget(self.frame, 1, 0, 3, 2)


        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)


        # 查看图片列表
        self.img_preview_list = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img_preview_list.sizePolicy().hasHeightForWidth())
        self.img_preview_list.setSizePolicy(sizePolicy)
        self.img_preview_list.setMinimumSize(QtCore.QSize(151, 0))
        self.img_preview_list.setMaximumSize(QtCore.QSize(151, 16777215))
        self.img_preview_list.setStyleSheet("")
        self.img_preview_list.setFrameShape(QtWidgets.QFrame.Box)
        self.img_preview_list.setObjectName("img_preview_list")
        self.gridLayout.addWidget(self.img_preview_list, 1, 5, 3, 1)



        self.mid_box = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mid_box.sizePolicy().hasHeightForWidth())
        self.mid_box.setSizePolicy(sizePolicy)
        self.mid_box.setMinimumSize(QtCore.QSize(151, 0))
        self.mid_box.setMaximumSize(QtCore.QSize(1920, 16777215))
        self.mid_box.setStyleSheet("QFrame#mid_box{border:1px solid #828790}")
        self.mid_box.setObjectName("mid_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mid_box)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")


        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)


        self.set_3x3_button = QtWidgets.QPushButton(self.mid_box)
        self.set_3x3_button.setObjectName("set_3x3_button")
        self.verticalLayout.addWidget(self.set_3x3_button)


        self.set_5x5_button = QtWidgets.QPushButton(self.mid_box)
        self.set_5x5_button.setObjectName("set_5x5_button")
        self.verticalLayout.addWidget(self.set_5x5_button)

        self.save_img_button = QtWidgets.QPushButton(self.mid_box)
        self.save_img_button.setObjectName("save_img_button")
        self.verticalLayout.addWidget(self.save_img_button)


        # 起始行、起始列，占用行，占用列
        self.gridLayout.addWidget(self.mid_box, 1, 3, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 23))
        self.menubar.setObjectName("menubar")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menuopen")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_open_big_img = QtWidgets.QAction(MainWindow)
        self.action_open_big_img.setObjectName("action_open_big_img")
        self.action_change_img_save_path = QtWidgets.QAction(MainWindow)
        self.action_change_img_save_path.setObjectName("action_change_img_save_path")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.menuopen.addAction(self.action_open_big_img)
        self.menuopen.addAction(self.action_change_img_save_path)
        self.menu.addAction(self.action_help)
        self.menubar.addAction(self.menuopen.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.prev_button, self.next_button)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "查看结果"))
        self.prev_button.setText(_translate("MainWindow", "上一张"))
        self.next_button.setText(_translate("MainWindow", "下一张"))

        self.set_3x3_button.setText(_translate("MainWindow", "查看周边3x3图片块"))
        self.set_5x5_button.setText(_translate("MainWindow", "查看周边5x5图片块"))
        self.save_img_button.setText(_translate("MainWindow", "保存图片块"))

        self.menuopen.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.action_open_big_img.setText(_translate("MainWindow", "打开大视场图像"))
        self.action_change_img_save_path.setText(_translate("MainWindow", "改变图像保存路径"))
        self.action_help.setText(_translate("MainWindow", "打开帮助窗口"))
